"""Compatibility façade for the provider-backed suitability engine."""

from app.ai.providers.rule_based.suitability import (
    DRAINAGE_LEVELS,
    RuleBasedSuitabilityProvider,
    SuitabilityScorer,
    build_penalties,
    calculate_suitability,
    evaluate_blockers,
    normalize_total_score,
    score_drainage,
    score_drainage_compatibility,
    score_irrigation,
    score_nutrient,
    score_ph,
    score_ph_compatibility,
    score_slope,
    score_slope_compatibility,
    score_soil_compatibility,
    score_soil_texture,
    score_water_availability,
)

__all__ = [
    "DRAINAGE_LEVELS",
    "RuleBasedSuitabilityProvider",
    "SuitabilityScorer",
    "build_penalties",
    "calculate_suitability",
    "evaluate_blockers",
    "normalize_total_score",
    "score_drainage",
    "score_drainage_compatibility",
    "score_irrigation",
    "score_nutrient",
    "score_ph",
    "score_ph_compatibility",
    "score_slope",
    "score_slope_compatibility",
    "score_soil_compatibility",
    "score_soil_texture",
    "score_water_availability",
]
