"""Deterministic placeholder explanation provider."""

from __future__ import annotations

from datetime import datetime, timezone

from app.ai.contracts.explanation import (
    ExplanationInput,
    ExplanationOutput,
    ExplanationProvider,
    RankedExplanationRequest,
    SuitabilityExplanationRequest,
    adapt_explanation_output,
    build_explanation_input_from_ranked_request,
    build_explanation_input_from_suitability_request,
)
from app.ai.contracts.metadata import AITraceMetadata
from app.ai.contracts.risk import RiskScorer
from app.ai.providers.rule_based.explanation import RuleBasedExplanationProvider
from app.ai.providers.stub.common import STUB_PROVIDER_SUFFIX, as_sentence, normalize_text
from app.ai.providers.stub.risk import StubRiskScorer
from app.schemas.explanation import FieldExplanation

_SHORT_PREFIX = "Stub explanation:"
_DETAIL_SUFFIX = (
    "This explanation was generated by DeterministicExplanationProvider for integration and test use."
)


class DeterministicExplanationProvider(ExplanationProvider):
    """Wrap rule-based explanations with stable placeholder metadata."""

    def __init__(self, risk_provider: RiskScorer | None = None) -> None:
        self.risk_provider = risk_provider or StubRiskScorer()
        self._delegate = RuleBasedExplanationProvider(risk_provider=self.risk_provider)

    def explain(self, request: ExplanationInput) -> ExplanationOutput:
        """Return a deterministic placeholder explanation for a canonical request."""

        explanation = self._delegate.explain(request)
        return self._decorate(explanation, field_name=request.ranking_result.field_name)

    def explain_suitability(self, request: SuitabilityExplanationRequest) -> FieldExplanation:
        """Return a deterministic placeholder explanation for a suitability result."""

        return adapt_explanation_output(
            self.explain(build_explanation_input_from_suitability_request(request))
        )

    def explain_ranked_result(self, request: RankedExplanationRequest) -> FieldExplanation:
        """Return a deterministic placeholder explanation for a ranked result."""

        return adapt_explanation_output(
            self.explain(build_explanation_input_from_ranked_request(request))
        )

    def _decorate(self, explanation: ExplanationOutput, *, field_name: str) -> ExplanationOutput:
        strengths = explanation.strengths or [
            f"{field_name} has enough structured agronomic input for deterministic placeholder analysis."
        ]
        weaknesses = explanation.weaknesses or [
            "Detailed agronomic explanation is currently being served by a deterministic stub provider."
        ]
        risks = explanation.risks or [f"No material agronomic risks detected from current stub inputs. {STUB_PROVIDER_SUFFIX}"]

        short_explanation = normalize_text(explanation.short_explanation)
        if not short_explanation.lower().startswith(_SHORT_PREFIX.lower()):
            short_explanation = f"{_SHORT_PREFIX} {short_explanation or f'{field_name} remains suitable under placeholder logic.'}"

        detailed_explanation = normalize_text(explanation.detailed_explanation)
        if _DETAIL_SUFFIX not in detailed_explanation:
            detailed_explanation = f"{detailed_explanation} {as_sentence(_DETAIL_SUFFIX)}".strip()

        return ExplanationOutput(
            short_explanation=as_sentence(short_explanation),
            detailed_explanation=normalize_text(detailed_explanation),
            strengths=strengths,
            weaknesses=weaknesses,
            risks=risks,
            confidence_note=explanation.confidence_note,
            metadata=AITraceMetadata(
                provider_name="deterministic_stub_provider",
                provider_version="v1",
                generated_at=datetime.now(timezone.utc),
                confidence=explanation.confidence,
                debug_info={
                    **(explanation.debug_info or {}),
                    "stub": True,
                },
            ),
        )
